version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack-full:0.12.6
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=us-west-2
      - SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,es,firehose,iam,kinesis,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=debug

      # DOCKER_CMD="sudo docker"
      # Use these if mounting from local drive in serverless.yml
      # - HOST_TMP_FOLDER=${PWD}/.localstack      
      # - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
